FROM node:16-buster

# Create app directory
WORKDIR /app

# Install app dependencies
# RUN npm -g install serve
RUN npm -g install gatsby-cli

COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

# serve on port 8080
CMD ["gatsby", "develop", "-p", "8080", "--host", "0.0.0.0"]
