services:
  server:
    build: ./server/
    links:
    - openssh-server
    volumes:
    - public-volume:/public
    - keys-volume:/keys
    environment:
    - PUBLIC_PATH=/public
    - SSH_HOST=openssh-server
    - SSH_PORT=2222
    - SSH_USER=workshop
    - SSH_PRIVATE_KEY=/keys/id_rsa
    healthcheck:
      test: 'curl localhost:3000/healthcheck'
      interval: "60s"
      timeout: "10s"
      start_period: "20s"
      retries: 5

  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile-dev
    links:
    - server
    environment:
    - MARKDOWN_PATH=/content
    - CHOKIDAR_USEPOLLING=1
    volumes:
    - public-volume:/app/public
    - ${CONTENT_PATH:-./content}:/content
    healthcheck:
      test: 'curl localhost:8080'
      interval: "60s"
      timeout: "10s"
      start_period: "120s"
      retries: 5

  openssh-server:
    build: ./ssh/
    hostname: workshop
    volumes:
    - keys-volume:/keys
    restart: unless-stopped

  nginx: 
    image: nginx:latest
    links:
    - frontend
    - server
    ports:
    - 8080:8080
    volumes:
    - ./dev/nginx.conf:/etc/nginx/nginx.conf

volumes:
  public-volume:
  keys-volume: